substitutions:
  _REGION: us-central1
  _REPO: dlv-book
  _IMAGE_NAME: dlv-book-jobs
  _DB_URI_SECRET: db-uri   # Secret Manager に登録しておく

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args: [
      "build",
      "-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$SHORT_SHA",
      "."
    ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: ensure-ar-repo
    entrypoint: bash
    args: ["-lc",
      "gcloud artifacts repositories describe ${_REPO} --location=${_REGION} || \
       gcloud artifacts repositories create ${_REPO} --repository-format=Docker --location=${_REGION}"
    ]

  - name: gcr.io/cloud-builders/docker
    id: push
    args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$SHORT_SHA"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-jobs
    entrypoint: bash
    args: ["-lc", 
      "IMG='${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$SHORT_SHA'; \
       gcloud run jobs deploy job1 --image $IMG --region ${_REGION} --args=job1 \
         --set-secrets=DB_URI=${_DB_URI_SECRET}:latest --task-timeout=30m --max-retries=1"
    ]

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
